/**
 *
 * @author akash
 */
package Project1;

import javax.swing.JOptionPane;
import java.sql.*;
import java.awt.Toolkit;

public class BillingSystem extends javax.swing.JFrame {
    
    //Declaring Variables for the calculator
    String operations;
    String answers;
    String a1;
    String f,f1,f2,f3,f4,f5,f6,f7,f8,f9;
    double a,b,c,d,e,g,h,i,j,k,m;
    double firstnum, secondnum, result;

    /**
     * Creates new form BillingSystem
     */
    public BillingSystem() {
        initComponents();
        SetIcon();
        MyTitle();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtDisplay = new javax.swing.JTextField();
        b8 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        badd = new javax.swing.JButton();
        bsub = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        bmul = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        bslash = new javax.swing.JButton();
        bdivide = new javax.swing.JButton();
        bdot = new javax.swing.JButton();
        bans = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        bclear = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        check2 = new javax.swing.JCheckBox();
        check3 = new javax.swing.JCheckBox();
        check1 = new javax.swing.JCheckBox();
        check4 = new javax.swing.JCheckBox();
        check5 = new javax.swing.JCheckBox();
        check6 = new javax.swing.JCheckBox();
        check11 = new javax.swing.JCheckBox();
        check10 = new javax.swing.JCheckBox();
        check9 = new javax.swing.JCheckBox();
        check8 = new javax.swing.JCheckBox();
        check7 = new javax.swing.JCheckBox();
        q2 = new javax.swing.JTextField();
        q1 = new javax.swing.JTextField();
        q4 = new javax.swing.JTextField();
        q3 = new javax.swing.JTextField();
        q5 = new javax.swing.JTextField();
        q6 = new javax.swing.JTextField();
        q7 = new javax.swing.JTextField();
        q8 = new javax.swing.JTextField();
        q9 = new javax.swing.JTextField();
        q10 = new javax.swing.JTextField();
        q11 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        deliverycharges = new javax.swing.JTextField();
        total1 = new javax.swing.JTextField();
        cgst = new javax.swing.JTextField();
        sgst = new javax.swing.JTextField();
        itemcost = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        v11 = new javax.swing.JTextField();
        v10 = new javax.swing.JTextField();
        v9 = new javax.swing.JTextField();
        v8 = new javax.swing.JTextField();
        v7 = new javax.swing.JTextField();
        v6 = new javax.swing.JTextField();
        v5 = new javax.swing.JTextField();
        v4 = new javax.swing.JTextField();
        v3 = new javax.swing.JTextField();
        v2 = new javax.swing.JTextField();
        v1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        taxtotal = new javax.swing.JTextField();
        total2 = new javax.swing.JTextField();
        subtotal = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        allclear = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 204));
        setMaximumSize(new java.awt.Dimension(1300, 650));
        setPreferredSize(new java.awt.Dimension(1300, 650));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(330, 360));
        jPanel1.setLayout(null);

        txtDisplay.setEditable(false);
        txtDisplay.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        txtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDisplayActionPerformed(evt);
            }
        });
        jPanel1.add(txtDisplay);
        txtDisplay.setBounds(10, 10, 310, 50);

        b8.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        b8.setText("8");
        b8.setPreferredSize(new java.awt.Dimension(60, 50));
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        jPanel1.add(b8);
        b8.setBounds(80, 70, 60, 50);

        b7.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        b7.setText("7");
        b7.setPreferredSize(new java.awt.Dimension(60, 50));
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        jPanel1.add(b7);
        b7.setBounds(10, 70, 60, 50);

        b9.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        b9.setText("9");
        b9.setPreferredSize(new java.awt.Dimension(60, 50));
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        jPanel1.add(b9);
        b9.setBounds(150, 70, 60, 50);

        badd.setBackground(new java.awt.Color(51, 51, 255));
        badd.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        badd.setForeground(new java.awt.Color(240, 240, 240));
        badd.setText("+");
        badd.setPreferredSize(new java.awt.Dimension(60, 50));
        badd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baddActionPerformed(evt);
            }
        });
        jPanel1.add(badd);
        badd.setBounds(220, 70, 60, 50);

        bsub.setBackground(new java.awt.Color(51, 51, 255));
        bsub.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        bsub.setForeground(new java.awt.Color(240, 240, 240));
        bsub.setText("-");
        bsub.setPreferredSize(new java.awt.Dimension(60, 50));
        bsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsubActionPerformed(evt);
            }
        });
        jPanel1.add(bsub);
        bsub.setBounds(220, 130, 60, 50);

        b6.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        b6.setText("6");
        b6.setPreferredSize(new java.awt.Dimension(60, 50));
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel1.add(b6);
        b6.setBounds(150, 130, 60, 50);

        b5.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        b5.setText("5");
        b5.setPreferredSize(new java.awt.Dimension(60, 50));
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        jPanel1.add(b5);
        b5.setBounds(80, 130, 60, 50);

        b4.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        b4.setText("4");
        b4.setPreferredSize(new java.awt.Dimension(60, 50));
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel1.add(b4);
        b4.setBounds(10, 130, 60, 50);

        bmul.setBackground(new java.awt.Color(51, 51, 255));
        bmul.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        bmul.setForeground(new java.awt.Color(240, 240, 240));
        bmul.setText("*");
        bmul.setPreferredSize(new java.awt.Dimension(60, 50));
        bmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmulActionPerformed(evt);
            }
        });
        jPanel1.add(bmul);
        bmul.setBounds(220, 190, 60, 50);

        b3.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        b3.setText("3");
        b3.setPreferredSize(new java.awt.Dimension(60, 50));
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel1.add(b3);
        b3.setBounds(150, 190, 60, 50);

        b2.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        b2.setText("2");
        b2.setPreferredSize(new java.awt.Dimension(60, 50));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2);
        b2.setBounds(80, 190, 60, 50);

        b1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        b1.setText("1");
        b1.setPreferredSize(new java.awt.Dimension(60, 50));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1);
        b1.setBounds(10, 190, 60, 50);

        bslash.setBackground(new java.awt.Color(51, 51, 255));
        bslash.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        bslash.setForeground(new java.awt.Color(240, 240, 240));
        bslash.setText("/");
        bslash.setPreferredSize(new java.awt.Dimension(60, 50));
        bslash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bslashActionPerformed(evt);
            }
        });
        jPanel1.add(bslash);
        bslash.setBounds(220, 250, 60, 50);

        bdivide.setBackground(new java.awt.Color(51, 51, 255));
        bdivide.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        bdivide.setForeground(new java.awt.Color(240, 240, 240));
        bdivide.setText("%");
        bdivide.setPreferredSize(new java.awt.Dimension(60, 50));
        bdivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdivideActionPerformed(evt);
            }
        });
        jPanel1.add(bdivide);
        bdivide.setBounds(150, 250, 60, 50);

        bdot.setBackground(new java.awt.Color(51, 51, 255));
        bdot.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        bdot.setForeground(new java.awt.Color(240, 240, 240));
        bdot.setText(".");
        bdot.setPreferredSize(new java.awt.Dimension(60, 50));
        bdot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdotActionPerformed(evt);
            }
        });
        jPanel1.add(bdot);
        bdot.setBounds(80, 250, 60, 50);

        bans.setBackground(new java.awt.Color(51, 51, 255));
        bans.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        bans.setForeground(new java.awt.Color(240, 240, 240));
        bans.setText("=");
        bans.setPreferredSize(new java.awt.Dimension(60, 50));
        bans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bansActionPerformed(evt);
            }
        });
        jPanel1.add(bans);
        bans.setBounds(150, 310, 130, 40);

        b0.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        b0.setText("0");
        b0.setPreferredSize(new java.awt.Dimension(60, 50));
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });
        jPanel1.add(b0);
        b0.setBounds(10, 250, 60, 50);

        bclear.setBackground(new java.awt.Color(51, 51, 255));
        bclear.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        bclear.setForeground(new java.awt.Color(240, 240, 240));
        bclear.setText("CE");
        bclear.setPreferredSize(new java.awt.Dimension(60, 50));
        bclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclearActionPerformed(evt);
            }
        });
        jPanel1.add(bclear);
        bclear.setBounds(10, 310, 130, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 60, 330, 370);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setPreferredSize(new java.awt.Dimension(930, 370));
        jPanel3.setLayout(null);

        check2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        check2.setText("French fries");
        check2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check2ActionPerformed(evt);
            }
        });
        jPanel3.add(check2);
        check2.setBounds(10, 40, 117, 31);

        check3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        check3.setText("Momo(Vg)");
        check3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check3ActionPerformed(evt);
            }
        });
        jPanel3.add(check3);
        check3.setBounds(10, 70, 111, 31);

        check1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        check1.setText("Chilli Potato");
        check1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check1ActionPerformed(evt);
            }
        });
        jPanel3.add(check1);
        check1.setBounds(10, 10, 130, 31);

        check4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        check4.setText("Momo(Ch)");
        check4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check4ActionPerformed(evt);
            }
        });
        jPanel3.add(check4);
        check4.setBounds(10, 100, 113, 31);

        check5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        check5.setText("Burger(vg)");
        check5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check5ActionPerformed(evt);
            }
        });
        jPanel3.add(check5);
        check5.setBounds(10, 130, 109, 31);

        check6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        check6.setText("Burger(Ch)");
        check6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check6ActionPerformed(evt);
            }
        });
        jPanel3.add(check6);
        check6.setBounds(10, 160, 113, 31);

        check11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        check11.setText("Hot Dog");
        check11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check11ActionPerformed(evt);
            }
        });
        jPanel3.add(check11);
        check11.setBounds(10, 310, 93, 31);

        check10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        check10.setText("Maggie");
        check10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check10ActionPerformed(evt);
            }
        });
        jPanel3.add(check10);
        check10.setBounds(10, 280, 83, 31);

        check9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        check9.setText("Omlette");
        check9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check9ActionPerformed(evt);
            }
        });
        jPanel3.add(check9);
        check9.setBounds(10, 250, 87, 31);

        check8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        check8.setText("Sandwich(Ch)");
        check8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check8ActionPerformed(evt);
            }
        });
        jPanel3.add(check8);
        check8.setBounds(10, 220, 140, 31);

        check7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        check7.setText("Sandwich(Vg)");
        check7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check7ActionPerformed(evt);
            }
        });
        jPanel3.add(check7);
        check7.setBounds(10, 190, 140, 31);

        q2.setEditable(false);
        q2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        q2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        q2.setText("0");
        jPanel3.add(q2);
        q2.setBounds(150, 50, 90, 23);

        q1.setEditable(false);
        q1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        q1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        q1.setText("0");
        q1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1ActionPerformed(evt);
            }
        });
        jPanel3.add(q1);
        q1.setBounds(150, 20, 90, 23);

        q4.setEditable(false);
        q4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        q4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        q4.setText("0");
        jPanel3.add(q4);
        q4.setBounds(150, 110, 90, 23);

        q3.setEditable(false);
        q3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        q3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        q3.setText("0");
        jPanel3.add(q3);
        q3.setBounds(150, 80, 90, 23);

        q5.setEditable(false);
        q5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        q5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        q5.setText("0");
        jPanel3.add(q5);
        q5.setBounds(150, 140, 90, 23);

        q6.setEditable(false);
        q6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        q6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        q6.setText("0");
        jPanel3.add(q6);
        q6.setBounds(150, 170, 90, 23);

        q7.setEditable(false);
        q7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        q7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        q7.setText("0");
        jPanel3.add(q7);
        q7.setBounds(150, 200, 90, 23);

        q8.setEditable(false);
        q8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        q8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        q8.setText("0");
        jPanel3.add(q8);
        q8.setBounds(150, 230, 90, 23);

        q9.setEditable(false);
        q9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        q9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        q9.setText("0");
        jPanel3.add(q9);
        q9.setBounds(150, 260, 90, 23);

        q10.setEditable(false);
        q10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        q10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        q10.setText("0");
        jPanel3.add(q10);
        q10.setBounds(150, 290, 90, 23);

        q11.setEditable(false);
        q11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        q11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        q11.setText("0");
        jPanel3.add(q11);
        q11.setBounds(150, 320, 90, 23);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel1.setText("Delivery charge");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 70, 170, 37);

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel2.setText("Total cost of items");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 30, 180, 37);

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel3.setText("CGST");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 150, 170, 37);

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel4.setText("SGST");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 110, 170, 37);

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel5.setText("Total Amount");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 250, 170, 37);

        deliverycharges.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        deliverycharges.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        deliverycharges.setText("0");
        jPanel2.add(deliverycharges);
        deliverycharges.setBounds(190, 70, 110, 30);

        total1.setEditable(false);
        total1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        total1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        total1.setText("0");
        jPanel2.add(total1);
        total1.setBounds(180, 240, 120, 50);

        cgst.setEditable(false);
        cgst.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        cgst.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cgst.setText("0");
        jPanel2.add(cgst);
        cgst.setBounds(190, 150, 110, 30);

        sgst.setEditable(false);
        sgst.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        sgst.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sgst.setText("0");
        jPanel2.add(sgst);
        sgst.setBounds(190, 110, 110, 30);

        itemcost.setEditable(false);
        itemcost.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        itemcost.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        itemcost.setText("0");
        jPanel2.add(itemcost);
        itemcost.setBounds(190, 30, 110, 30);

        jPanel3.add(jPanel2);
        jPanel2.setBounds(450, 10, 310, 330);

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(240, 240, 240));
        jButton1.setText("Value");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(250, 50, 80, 25);

        jButton2.setBackground(new java.awt.Color(0, 0, 255));
        jButton2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(240, 240, 240));
        jButton2.setText("Value");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(250, 20, 80, 25);

        jButton3.setBackground(new java.awt.Color(0, 0, 255));
        jButton3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(240, 240, 240));
        jButton3.setText("Value");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(250, 110, 80, 25);

        jButton4.setBackground(new java.awt.Color(0, 0, 255));
        jButton4.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(240, 240, 240));
        jButton4.setText("Value");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(250, 80, 80, 25);

        jButton5.setBackground(new java.awt.Color(0, 0, 255));
        jButton5.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(240, 240, 240));
        jButton5.setText("Value");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);
        jButton5.setBounds(250, 200, 80, 25);

        jButton6.setBackground(new java.awt.Color(0, 0, 255));
        jButton6.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(240, 240, 240));
        jButton6.setText("Value");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(250, 230, 80, 25);

        jButton7.setBackground(new java.awt.Color(0, 0, 255));
        jButton7.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(240, 240, 240));
        jButton7.setText("Value");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);
        jButton7.setBounds(250, 140, 80, 25);

        jButton8.setBackground(new java.awt.Color(0, 0, 255));
        jButton8.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(240, 240, 240));
        jButton8.setText("Value");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8);
        jButton8.setBounds(250, 170, 80, 25);

        jButton9.setBackground(new java.awt.Color(0, 0, 255));
        jButton9.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(240, 240, 240));
        jButton9.setText("Value");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9);
        jButton9.setBounds(250, 260, 80, 25);

        jButton10.setBackground(new java.awt.Color(0, 0, 255));
        jButton10.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(240, 240, 240));
        jButton10.setText("Value");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10);
        jButton10.setBounds(250, 290, 80, 25);

        jButton11.setBackground(new java.awt.Color(0, 0, 255));
        jButton11.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(240, 240, 240));
        jButton11.setText("Value");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11);
        jButton11.setBounds(250, 320, 80, 25);

        v11.setEditable(false);
        v11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        v11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v11.setText("0");
        jPanel3.add(v11);
        v11.setBounds(340, 320, 90, 23);

        v10.setEditable(false);
        v10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        v10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v10.setText("0");
        jPanel3.add(v10);
        v10.setBounds(340, 290, 90, 23);

        v9.setEditable(false);
        v9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        v9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v9.setText("0");
        jPanel3.add(v9);
        v9.setBounds(340, 260, 90, 23);

        v8.setEditable(false);
        v8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        v8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v8.setText("0");
        jPanel3.add(v8);
        v8.setBounds(340, 230, 90, 23);

        v7.setEditable(false);
        v7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        v7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v7.setText("0");
        jPanel3.add(v7);
        v7.setBounds(340, 200, 90, 23);

        v6.setEditable(false);
        v6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        v6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v6.setText("0");
        jPanel3.add(v6);
        v6.setBounds(340, 170, 90, 23);

        v5.setEditable(false);
        v5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        v5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v5.setText("0");
        jPanel3.add(v5);
        v5.setBounds(340, 140, 90, 23);

        v4.setEditable(false);
        v4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        v4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v4.setText("0");
        jPanel3.add(v4);
        v4.setBounds(340, 110, 90, 23);

        v3.setEditable(false);
        v3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        v3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v3.setText("0");
        jPanel3.add(v3);
        v3.setBounds(340, 80, 90, 23);

        v2.setEditable(false);
        v2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        v2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v2.setText("0");
        jPanel3.add(v2);
        v2.setBounds(340, 50, 90, 23);

        v1.setEditable(false);
        v1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        v1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v1.setText("0");
        jPanel3.add(v1);
        v1.setBounds(340, 20, 90, 23);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel10.setText("Name");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(10, 20, 110, 30);
        jPanel5.add(name);
        name.setBounds(10, 60, 130, 30);

        jLabel11.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        jLabel11.setText("Contact no.");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(10, 110, 130, 40);
        jPanel5.add(contact);
        contact.setBounds(10, 160, 130, 30);

        jPanel3.add(jPanel5);
        jPanel5.setBounds(770, 10, 150, 330);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(350, 60, 930, 370);

        jLabel7.setBackground(new java.awt.Color(0, 255, 204));
        jLabel7.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("  Appetite Billing System");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(210, 10, 850, 40);

        jPanel4.setBackground(new java.awt.Color(51, 51, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setPreferredSize(new java.awt.Dimension(1250, 110));
        jPanel4.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Total ");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(150, 89, 100, 40);

        jLabel8.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Subtotal");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(150, 9, 140, 40);

        jLabel9.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Tax Total");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(150, 50, 140, 40);

        taxtotal.setEditable(false);
        taxtotal.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        taxtotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        taxtotal.setText("Rs. 0.00");
        taxtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxtotalActionPerformed(evt);
            }
        });
        jPanel4.add(taxtotal);
        taxtotal.setBounds(300, 50, 290, 30);

        total2.setEditable(false);
        total2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        total2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        total2.setText("Rs. 0.00");
        total2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total2ActionPerformed(evt);
            }
        });
        jPanel4.add(total2);
        total2.setBounds(300, 90, 290, 30);

        subtotal.setEditable(false);
        subtotal.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        subtotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        subtotal.setText("Rs. 0.00");
        subtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtotalActionPerformed(evt);
            }
        });
        jPanel4.add(subtotal);
        subtotal.setBounds(300, 10, 290, 30);

        jButton12.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jButton12.setText("Calculate");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton12);
        jButton12.setBounds(660, 60, 180, 40);

        allclear.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        allclear.setText("Clear");
        allclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allclearActionPerformed(evt);
            }
        });
        jPanel4.add(allclear);
        allclear.setBounds(660, 10, 180, 40);

        jButton13.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jButton13.setText("Record");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton13);
        jButton13.setBounds(970, 50, 110, 50);

        jButton14.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jButton14.setText("EXIT");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton14);
        jButton14.setBounds(1119, 50, 110, 50);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(20, 460, 1250, 140);

        pack();
    }// </editor-fold>                        

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        String EnterNumber = txtDisplay.getText() + b7.getText();
        txtDisplay.setText(EnterNumber);  
    }                                  

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        String EnterNumber = txtDisplay.getText() + b9.getText();
        txtDisplay.setText(EnterNumber);  
    }                                  

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        String EnterNumber = txtDisplay.getText() + b2.getText();
        txtDisplay.setText(EnterNumber);  
    }                                  

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        String EnterNumber = txtDisplay.getText() + b0.getText();
        txtDisplay.setText(EnterNumber);       
    }                                  

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        String EnterNumber = txtDisplay.getText() + b8.getText();
        txtDisplay.setText(EnterNumber);         
    }                                  

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        String EnterNumber = txtDisplay.getText() + b4.getText();
        txtDisplay.setText(EnterNumber);         
    }                                  

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        String EnterNumber = txtDisplay.getText() + b5.getText();
        txtDisplay.setText(EnterNumber);         
    }                                  

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        String EnterNumber = txtDisplay.getText() + b6.getText();
        txtDisplay.setText(EnterNumber);         
    }                                  

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        String EnterNumber = txtDisplay.getText() + b1.getText();
        txtDisplay.setText(EnterNumber);         
    }                                  

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        String EnterNumber = txtDisplay.getText() + b3.getText();
        txtDisplay.setText(EnterNumber);         
    }                                  

    private void bdotActionPerformed(java.awt.event.ActionEvent evt) {                                     
        if(!txtDisplay.getText().contains(".")) // means if there's any dot present or not
        {
            txtDisplay.setText(txtDisplay.getText() + bdot.getText());//happens if no dot is there 
        }

    }                                    

    private void baddActionPerformed(java.awt.event.ActionEvent evt) {                                     
        firstnum = Double.parseDouble(txtDisplay.getText()); //converts the string into double 
        txtDisplay.setText("");
        operations = "+";
    }                                    

    private void bsubActionPerformed(java.awt.event.ActionEvent evt) {                                     
        firstnum = Double.parseDouble(txtDisplay.getText()); //converts the string into double 
        txtDisplay.setText("");
        operations = "-";        
    }                                    

    private void bmulActionPerformed(java.awt.event.ActionEvent evt) {                                     
        firstnum = Double.parseDouble(txtDisplay.getText());  
        txtDisplay.setText("");
        operations = "*";        
    }                                    

    private void bslashActionPerformed(java.awt.event.ActionEvent evt) {                                       
        firstnum = Double.parseDouble(txtDisplay.getText()); //converts the string into double 
        txtDisplay.setText("");
        operations = "/";       
    }                                      

    private void bdivideActionPerformed(java.awt.event.ActionEvent evt) {                                        
        firstnum = Double.parseDouble(txtDisplay.getText()); //converts the string into double 
        txtDisplay.setText("");
        operations = "%";        
    }                                       

    private void bclearActionPerformed(java.awt.event.ActionEvent evt) {                                       
        txtDisplay.setText(" "); 
        
    }                                      

    private void check1ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        if(check1.isSelected())
        {
            q1.setEditable(true);
            q1.setText("");
            q1.requestFocus();
        }
        else
        {
            q1.setEditable(false);
            q1.setText("0");
        }
    }                                      

    private void bansActionPerformed(java.awt.event.ActionEvent evt) {                                     
        secondnum = Double.parseDouble(txtDisplay.getText());
        if(operations == "+")
        {
            result = firstnum + secondnum;
            answers = String.format("%.2f",result);
            txtDisplay.setText(answers);
        }
        else if(operations == "-")
        {
            result = firstnum - secondnum;
            answers = String.format("%.2f",result);
            txtDisplay.setText(answers);
        }
        else if(operations == "*")
        {
            result = firstnum * secondnum;
            answers = String.format("%.2f",result);
            txtDisplay.setText(answers);
        }
        else if(operations == "/")
        {
            result = firstnum/secondnum;
            answers = String.format("%.2f",result);
            txtDisplay.setText(answers);
        }
        else
        {
            result = firstnum%secondnum;
            answers = String.format("%.2f",result);
            txtDisplay.setText(answers);
        }
    }                                    

    private void subtotalActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
    }                                        

    private void allclearActionPerformed(java.awt.event.ActionEvent evt) {                                         
        txtDisplay.setText("");
        a=b=c=d=e=g=h=i=j=k=m=0;
        q1.setText("0");
        q2.setText("0");
        q3.setText("0");
        q4.setText("0");
        q5.setText("0");
        q6.setText("0");
        q7.setText("0");
        q8.setText("0");
        q9.setText("0");
        q10.setText("0");
        q11.setText("0");
        v1.setText("0");
        v2.setText("0");
        v3.setText("0");
        v4.setText("0");
        v5.setText("0");
        v6.setText("0");
        v7.setText("0");
        v8.setText("0");
        v9.setText("0");
        v10.setText("0");
        v11.setText("0");
        itemcost.setText("0");
        deliverycharges.setText("0");
        cgst.setText("0");
        sgst.setText("0");
        total1.setText("0");
        subtotal.setText("0.00");
        taxtotal.setText("0.00");
        total2.setText("0.00");
        check1.setSelected(false);
        check2.setSelected(false);
        check3.setSelected(false);
        check4.setSelected(false);
        check5.setSelected(false);
        check6.setSelected(false);
        check7.setSelected(false);
        check8.setSelected(false);
        check9.setSelected(false);
        check10.setSelected(false);
        check11.setSelected(false);
        name.setText("");
        contact.setText("");
        
        
    }                                        

    private void q1ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        
    }                                  

    private void taxtotalActionPerformed(java.awt.event.ActionEvent evt) {                                         
       
    }                                        

    private void check2ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        if(check2.isSelected())
            {
                q2.setEditable(true);
                q2.setText("");
                q2.requestFocus();//request focus means direct cursor will go
            }
        else
        {
            q2.setEditable(false);
            q2.setText("0");
        }        
    }                                      

    private void check3ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        if(check3.isSelected())
        {
            q3.setEditable(true);
            q3.setText("");
            q3.requestFocus();
        }
        else
        {
            q3.setEditable(false);
            q3.setText("0");
        }        
    }                                      

    private void check4ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        if(check4.isSelected())
        {
            q4.setEditable(true);
            q4.setText("");
            q4.requestFocus();
        }
        else
        {
            q4.setEditable(false);
            q4.setText("0");
        }        
    }                                      

    private void check5ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        if(check5.isSelected())
        {
            q5.setEditable(true);
            q5.setText("");
            q5.requestFocus();
        }
        else
        {
            q5.setEditable(false);
            q5.setText("0");
        }        
    }                                      

    private void check6ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        if(check6.isSelected())
        {
            q6.setEditable(true);
            q6.setText("");
            q6.requestFocus();
        }
        else
        {
            q6.setEditable(false);
            q6.setText("0");
        }        
    }                                      

    private void check7ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        if(check7.isSelected())
        {
            q7.setEditable(true);
            q7.setText("");
            q7.requestFocus();
        }
        else
        {
            q7.setEditable(false);
            q7.setText("0");
        }        
    }                                      

    private void check8ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        if(check8.isSelected())
        {
            q8.setEditable(true);
            q8.setText("");
            q8.requestFocus();
        }
        else
        {
            q8.setEditable(false);
            q8.setText("0");
        }        
    }                                      

    private void check9ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        if(check9.isSelected())
        {
            q9.setEditable(true);
            q9.setText("");
            q9.requestFocus();
        }
        else
        {
            q9.setEditable(false);
            q9.setText("0");
        }        
    }                                      

    private void check10ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        if(check10.isSelected())
        {
            q10.setEditable(true);
            q10.setText("");
            q10.requestFocus();
        }
        else
        {
            q10.setEditable(false);
            q10.setText("0");
        }        
    }                                       

    private void check11ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        if(check11.isSelected())
        {
            q11.setEditable(true);
            q11.setText("");
            q11.requestFocus();
        }
        else
        {
            q11.setEditable(false);
            q11.setText("0");
        }        
    }                                       

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        double itemcost1 = a+b+c+d+e+g+h+i+j+k+m;
        double itemtax = itemcost1*0.09;
        
        String itemcost2 = String.format("%.2f",itemcost1);
        itemcost.setText(itemcost2);
        double deliverycharge1 = Double.parseDouble(deliverycharges.getText());
        String sgstcharge1 = String.format("%.2f",itemtax);
        sgst.setText(sgstcharge1);
        cgst.setText(sgstcharge1);
        double alltotal1 = itemcost1 + itemtax + deliverycharge1+itemtax;
        String alltotal2 = String.format("%.2f",alltotal1);
        total1.setText(alltotal2);
        total2.setText(alltotal2);
        subtotal.setText(itemcost2);
        double taxtotal1= itemtax*2;
        String taxtotal2 = String.format("%.2f",taxtotal1);
        taxtotal.setText(taxtotal2);
        
    }                                         

    private void total2ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        
    }                                      

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(check1.isSelected())
        {
            a = Double.parseDouble(q1.getText())*60;
            a1 = String.format("%.2f",a);
            v1.setText(a1);
        }
        else
        {
            v1.setText("0");
            
        }
    }                                        

    private void txtDisplayActionPerformed(java.awt.event.ActionEvent evt) {                                           
        
    }                                          

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(check2.isSelected())
        {
            b = Double.parseDouble(q2.getText())*40;
            f = String.format("%.2f",b);
            v2.setText(f);
        }
        else
        {
            v2.setText("0");
        }
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(check3.isSelected())
        {
            c = Double.parseDouble(q3.getText())*50;
            f1 = String.format("%.2f",c);
            v3.setText(f1);
        }
        else
        {
            v3.setText("0");
        }        
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(check4.isSelected())
        {
            d = Double.parseDouble(q4.getText())*100;
            f2 = String.format("%.2f",d);
            v4.setText(f2);
        }
        else
        {
            v4.setText("0");
        }        
    }                                        

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(check5.isSelected())
        {
            e = Double.parseDouble(q5.getText())*60;
            f3 = String.format("%.2f",e);
            v5.setText(f3);
        }
        else
        {
            v5.setText("0");
        }        
    }                                        

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(check6.isSelected())
        {
            g = Double.parseDouble(q6.getText())*100;
            f4 = String.format("%.2f",g);
            v6.setText(f4);
        }
        else
        {
            v6.setText("0");
        }        
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    if(check7.isSelected())
        {
            h = Double.parseDouble(q7.getText())*140;
            f5 = String.format("%.2f",h);
            v7.setText(f5);
        }
        else
        {
            v7.setText("0");
        }        
    }                                        

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(check8.isSelected())
        {
            i = Double.parseDouble(q8.getText())*150;
            f6 = String.format("%.2f",i);
            v8.setText(f6);
        }
        else
        {
            v8.setText("0");
        }       
    }                                        

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(check9.isSelected())
        {
            j = Double.parseDouble(q9.getText())*50;
            f7 = String.format("%.2f",j);
            v9.setText(f7);
        }
        else
        {
            v9.setText("0");
        }        
    }                                        

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        if(check10.isSelected())
        {
            k = Double.parseDouble(q10.getText())*30;
            f8 = String.format("%.2f",k);
            v10.setText(f8);
        }
        else
        {
            v10.setText("0");
        }        
    }                                         

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        if(check11.isSelected())
        {
            m = Double.parseDouble(q11.getText())*40;
            f9 = String.format("%.2f",m);
            v11.setText(f9);
        }
        else
        {
            v11.setText("0");
        }        
    }                                         

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        this.dispose();
    }                                         
    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/appy","root","booty");
            PreparedStatement ps = conn.prepareStatement("INSERT INTO bill VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);");
            ps.setString(1,name.getText());
            ps.setString(2, contact.getText());
            ps.setInt(3,Integer.parseInt(q1.getText()));
            ps.setInt(4,Integer.parseInt(q2.getText()));
            ps.setInt(5,Integer.parseInt(q3.getText()));
            ps.setInt(6,Integer.parseInt(q4.getText()));
            ps.setInt(7,Integer.parseInt(q5.getText()));
            ps.setInt(8,Integer.parseInt(q6.getText()));
            ps.setInt(9,Integer.parseInt(q7.getText()));
            ps.setInt(10,Integer.parseInt(q8.getText()));
            ps.setInt(11,Integer.parseInt(q9.getText()));
            ps.setInt(12,Integer.parseInt(q10.getText()));
            ps.setInt(13,Integer.parseInt(q11.getText()));
            ps.setDouble(14,Double.parseDouble(subtotal.getText()));
            ps.setDouble(15,Double.parseDouble(deliverycharges.getText()));
            ps.setDouble(16,Double.parseDouble(taxtotal.getText()));
            ps.setDouble(17,Double.parseDouble(total2.getText()));
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Record Inserted!");
            conn.close();
        } catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error Occured! Couldn't insert data!");
        }
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillingSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton allclear;
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton badd;
    private javax.swing.JButton bans;
    private javax.swing.JButton bclear;
    private javax.swing.JButton bdivide;
    private javax.swing.JButton bdot;
    private javax.swing.JButton bmul;
    private javax.swing.JButton bslash;
    private javax.swing.JButton bsub;
    private javax.swing.JTextField cgst;
    private javax.swing.JCheckBox check1;
    private javax.swing.JCheckBox check10;
    private javax.swing.JCheckBox check11;
    private javax.swing.JCheckBox check2;
    private javax.swing.JCheckBox check3;
    private javax.swing.JCheckBox check4;
    private javax.swing.JCheckBox check5;
    private javax.swing.JCheckBox check6;
    private javax.swing.JCheckBox check7;
    private javax.swing.JCheckBox check8;
    private javax.swing.JCheckBox check9;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField deliverycharges;
    private javax.swing.JTextField itemcost;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField name;
    private javax.swing.JTextField q1;
    private javax.swing.JTextField q10;
    private javax.swing.JTextField q11;
    private javax.swing.JTextField q2;
    private javax.swing.JTextField q3;
    private javax.swing.JTextField q4;
    private javax.swing.JTextField q5;
    private javax.swing.JTextField q6;
    private javax.swing.JTextField q7;
    private javax.swing.JTextField q8;
    private javax.swing.JTextField q9;
    private javax.swing.JTextField sgst;
    private javax.swing.JTextField subtotal;
    private javax.swing.JTextField taxtotal;
    private javax.swing.JTextField total1;
    private javax.swing.JTextField total2;
    private javax.swing.JTextField txtDisplay;
    private javax.swing.JTextField v1;
    private javax.swing.JTextField v10;
    private javax.swing.JTextField v11;
    private javax.swing.JTextField v2;
    private javax.swing.JTextField v3;
    private javax.swing.JTextField v4;
    private javax.swing.JTextField v5;
    private javax.swing.JTextField v6;
    private javax.swing.JTextField v7;
    private javax.swing.JTextField v8;
    private javax.swing.JTextField v9;
    // End of variables declaration                   

    private void SetIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("fries.png")));
    }

    private void MyTitle() {
        setTitle("Billing System");
        
    }
}
